version: '3'

services:
  nx-app-base:
    build:
      context: ..
      dockerfile: ./docker-compose/Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ../:/app
      - mono-node-modules:/app/node_modules
